# fbm to telegram configuration template
# holds secret keys and user information

[users.sender]
name = "Alice"
api_id = 123456
api_hash = "API_HASH_ALICE"

[users.recipient]
name = "Bob"
api_id = 654321
api_hash = "API_HASH_BOB"

